/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.lexer.*;
import minipython.node.*;
import minipython.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;

        if(actionTable == null)
        {
            try
            {
                DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                    Parser.class.getResourceAsStream("parser.dat")));

                // read actionTable
                int length = s.readInt();
                actionTable = new int[length][][];
                for(int i = 0; i < actionTable.length; i++)
                {
                    length = s.readInt();
                    actionTable[i] = new int[length][3];
                    for(int j = 0; j < actionTable[i].length; j++)
                    {
                        for(int k = 0; k < 3; k++)
                        {
                            actionTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read gotoTable
                length = s.readInt();
                gotoTable = new int[length][][];
                for(int i = 0; i < gotoTable.length; i++)
                {
                    length = s.readInt();
                    gotoTable[i] = new int[length][2];
                    for(int j = 0; j < gotoTable[i].length; j++)
                    {
                        for(int k = 0; k < 2; k++)
                        {
                            gotoTable[i][j][k] = s.readInt();
                        }
                    }
                }

                // read errorMessages
                length = s.readInt();
                errorMessages = new String[length];
                for(int i = 0; i < errorMessages.length; i++)
                {
                    length = s.readInt();
                    StringBuffer buffer = new StringBuffer();

                    for(int j = 0; j < length; j++)
                    {
                        buffer.append(s.readChar());
                    }
                    errorMessages[i] = buffer.toString();
                }

                // read errors
                length = s.readInt();
                errors = new int[length];
                for(int i = 0; i < errors.length; i++)
                {
                    errors[i] = s.readInt();
                }

                s.close();
            }
            catch(Exception e)
            {
                throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
            }
        }
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
	this.nodeList = listNode;

        if(!stack.hasNext())
        {
            stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int state()
    {
        State s = (State) stack.previous();
        stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return (ArrayList) ((State) stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        converter.index = -1;
        token.apply(converter);
        return converter.index;
    }

    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);

        List ign = null;
        while(true)
        {
            while(index(lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedLinkedList(NodeCast.instance);
                }

                ign.add(lexer.next());
            }

            if(ign != null)
            {
                ignoredTokens.setIn(lexer.peek(), ign);
                ign = null;
            }

            last_pos = lexer.peek().getPos();
            last_line = lexer.peek().getLine();
            last_token = lexer.peek();

            int index = index(lexer.peek());
            action[0] = actionTable[state()][0][1];
            action[1] = actionTable[state()][0][2];

            int low = 1;
            int high = actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[state()][middle][1];
                    action[1] = actionTable[state()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(lexer.next());
                        push(action[1], list);
                        last_shift = action[1];
                    }
		    break;
                case REDUCE:
                    switch(action[1])
                    {

                    case 0:
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;


                    case 1:
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;


                    case 2:
		    {
			ArrayList list = new2();
			push(goTo(1), list);
		    }
		    break;


                    case 3:
		    {
			ArrayList list = new3();
			push(goTo(1), list);
		    }
		    break;


                    case 4:
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;


                    case 5:
		    {
			ArrayList list = new5();
			push(goTo(2), list);
		    }
		    break;


                    case 6:
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;


                    case 7:
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;


                    case 8:
		    {
			ArrayList list = new8();
			push(goTo(3), list);
		    }
		    break;


                    case 9:
		    {
			ArrayList list = new9();
			push(goTo(3), list);
		    }
		    break;


                    case 10:
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;


                    case 11:
		    {
			ArrayList list = new11();
			push(goTo(5), list);
		    }
		    break;


                    case 12:
		    {
			ArrayList list = new12();
			push(goTo(5), list);
		    }
		    break;


                    case 13:
		    {
			ArrayList list = new13();
			push(goTo(6), list);
		    }
		    break;


                    case 14:
		    {
			ArrayList list = new14();
			push(goTo(6), list);
		    }
		    break;


                    case 15:
		    {
			ArrayList list = new15();
			push(goTo(6), list);
		    }
		    break;


                    case 16:
		    {
			ArrayList list = new16();
			push(goTo(6), list);
		    }
		    break;


                    case 17:
		    {
			ArrayList list = new17();
			push(goTo(6), list);
		    }
		    break;


                    case 18:
		    {
			ArrayList list = new18();
			push(goTo(6), list);
		    }
		    break;


                    case 19:
		    {
			ArrayList list = new19();
			push(goTo(6), list);
		    }
		    break;


                    case 20:
		    {
			ArrayList list = new20();
			push(goTo(6), list);
		    }
		    break;


                    case 21:
		    {
			ArrayList list = new21();
			push(goTo(6), list);
		    }
		    break;


                    case 22:
		    {
			ArrayList list = new22();
			push(goTo(6), list);
		    }
		    break;


                    case 23:
		    {
			ArrayList list = new23();
			push(goTo(6), list);
		    }
		    break;


                    case 24:
		    {
			ArrayList list = new24();
			push(goTo(6), list);
		    }
		    break;


                    case 25:
		    {
			ArrayList list = new25();
			push(goTo(6), list);
		    }
		    break;


                    case 26:
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;


                    case 27:
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;


                    case 28:
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;


                    case 29:
		    {
			ArrayList list = new29();
			push(goTo(6), list);
		    }
		    break;


                    case 30:
		    {
			ArrayList list = new30();
			push(goTo(6), list);
		    }
		    break;


                    case 31:
		    {
			ArrayList list = new31();
			push(goTo(7), list);
		    }
		    break;


                    case 32:
		    {
			ArrayList list = new32();
			push(goTo(7), list);
		    }
		    break;


                    case 33:
		    {
			ArrayList list = new33();
			push(goTo(7), list);
		    }
		    break;


                    case 34:
		    {
			ArrayList list = new34();
			push(goTo(7), list);
		    }
		    break;


                    case 35:
		    {
			ArrayList list = new35();
			push(goTo(7), list);
		    }
		    break;


                    case 36:
		    {
			ArrayList list = new36();
			push(goTo(7), list);
		    }
		    break;


                    case 37:
		    {
			ArrayList list = new37();
			push(goTo(8), list);
		    }
		    break;


                    case 38:
		    {
			ArrayList list = new38();
			push(goTo(8), list);
		    }
		    break;


                    case 39:
		    {
			ArrayList list = new39();
			push(goTo(9), list);
		    }
		    break;


                    case 40:
		    {
			ArrayList list = new40();
			push(goTo(9), list);
		    }
		    break;


                    case 41:
		    {
			ArrayList list = new41();
			push(goTo(10), list);
		    }
		    break;


                    case 42:
		    {
			ArrayList list = new42();
			push(goTo(10), list);
		    }
		    break;


                    case 43:
		    {
			ArrayList list = new43();
			push(goTo(11), list);
		    }
		    break;


                    case 44:
		    {
			ArrayList list = new44();
			push(goTo(12), list);
		    }
		    break;


                    case 45:
		    {
			ArrayList list = new45();
			push(goTo(12), list);
		    }
		    break;


                    case 46:
		    {
			ArrayList list = new46();
			push(goTo(12), list);
		    }
		    break;


                    case 47:
		    {
			ArrayList list = new47();
			push(goTo(13), list);
		    }
		    break;


                    case 48:
		    {
			ArrayList list = new48();
			push(goTo(13), list);
		    }
		    break;


                    case 49:
		    {
			ArrayList list = new49();
			push(goTo(13), list);
		    }
		    break;


                    case 50:
		    {
			ArrayList list = new50();
			push(goTo(14), list);
		    }
		    break;


                    case 51:
		    {
			ArrayList list = new51();
			push(goTo(14), list);
		    }
		    break;


                    case 52:
		    {
			ArrayList list = new52();
			push(goTo(14), list);
		    }
		    break;


                    case 53:
		    {
			ArrayList list = new53();
			push(goTo(14), list);
		    }
		    break;


                    case 54:
		    {
			ArrayList list = new54();
			push(goTo(15), list);
		    }
		    break;


                    case 55:
		    {
			ArrayList list = new55();
			push(goTo(15), list);
		    }
		    break;


                    case 56:
		    {
			ArrayList list = new56();
			push(goTo(15), list);
		    }
		    break;


                    case 57:
		    {
			ArrayList list = new57();
			push(goTo(15), list);
		    }
		    break;


                    case 58:
		    {
			ArrayList list = new58();
			push(goTo(15), list);
		    }
		    break;


                    case 59:
		    {
			ArrayList list = new59();
			push(goTo(15), list);
		    }
		    break;


                    case 60:
		    {
			ArrayList list = new60();
			push(goTo(16), list);
		    }
		    break;


                    case 61:
		    {
			ArrayList list = new61();
			push(goTo(16), list);
		    }
		    break;


                    case 62:
		    {
			ArrayList list = new62();
			push(goTo(17), list);
		    }
		    break;


                    case 63:
		    {
			ArrayList list = new63();
			push(goTo(17), list);
		    }
		    break;


                    case 64:
		    {
			ArrayList list = new64();
			push(goTo(18), list);
		    }
		    break;


                    case 65:
		    {
			ArrayList list = new65();
			push(goTo(19), list);
		    }
		    break;


                    case 66:
		    {
			ArrayList list = new66();
			push(goTo(19), list);
		    }
		    break;


                    case 67:
		    {
			ArrayList list = new67();
			push(goTo(20), list);
		    }
		    break;


                    case 68:
		    {
			ArrayList list = new68();
			push(goTo(21), list);
		    }
		    break;


                    case 69:
		    {
			ArrayList list = new69();
			push(goTo(21), list);
		    }
		    break;


                    case 70:
		    {
			ArrayList list = new70();
			push(goTo(22), list);
		    }
		    break;


                    case 71:
		    {
			ArrayList list = new71();
			push(goTo(22), list);
		    }
		    break;


                    case 72:
		    {
			ArrayList list = new72();
			push(goTo(23), list);
		    }
		    break;


                    case 73:
		    {
			ArrayList list = new73();
			push(goTo(23), list);
		    }
		    break;


                    case 74:
		    {
			ArrayList list = new74();
			push(goTo(24), list);
		    }
		    break;


                    case 75:
		    {
			ArrayList list = new75();
			push(goTo(24), list);
		    }
		    break;


                    case 76:
		    {
			ArrayList list = new76();
			push(goTo(25), list);
		    }
		    break;


                    case 77:
		    {
			ArrayList list = new77();
			push(goTo(25), list);
		    }
		    break;

                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.next();
                        PGoal node1 = (PGoal) ((ArrayList)pop()).get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }



    ArrayList new0()
    {
        ArrayList nodeList = new ArrayList();

        PGoal pgoalNode1;
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        }

        pgoalNode1 = new ACmdsGoal(listNode2);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new1()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PGoal pgoalNode1;
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode2 = new TypedLinkedList();
        listNode2 = (TypedLinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pgoalNode1 = new ACmdsGoal(listNode3);
        }
	nodeList.add(pgoalNode1);
        return nodeList;
    }



    ArrayList new2()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PFunction pfunctionNode2;
        pfunctionNode2 = (PFunction)nodeArrayList1.get(0);

        pcommandsNode1 = new AFuncCommands(pfunctionNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new3()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PCommands pcommandsNode1;
        {
        PStatement pstatementNode2;
        pstatementNode2 = (PStatement)nodeArrayList1.get(0);

        pcommandsNode1 = new AStatementCommands(pstatementNode2);
        }
	nodeList.add(pcommandsNode1);
        return nodeList;
    }



    ArrayList new4()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pfunctionNode1 = new AFuncFunction(tidNode2, null, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new5()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunction pfunctionNode1;
        {
        TId tidNode2;
        PArgument pargumentNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pargumentNode3 = (PArgument)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pfunctionNode1 = new AFuncFunction(tidNode2, pargumentNode3, pstatementNode4);
        }
	nodeList.add(pfunctionNode1);
        return nodeList;
    }



    ArrayList new6()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        }

        pargumentNode1 = new AArgArgument(tidNode2, null, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new7()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        PAssignValue passignvalueNode3;
        TypedLinkedList listNode4 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        passignvalueNode3 = (PAssignValue)nodeArrayList2.get(0);
        {
        }

        pargumentNode1 = new AArgArgument(tidNode2, passignvalueNode3, listNode4);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new8()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgArgument(tidNode2, null, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new9()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgument pargumentNode1;
        {
        TId tidNode2;
        PAssignValue passignvalueNode3;
        TypedLinkedList listNode5 = new TypedLinkedList();
        tidNode2 = (TId)nodeArrayList1.get(0);
        passignvalueNode3 = (PAssignValue)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode4 = new TypedLinkedList();
        listNode4 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pargumentNode1 = new AArgArgument(tidNode2, passignvalueNode3, listNode5);
        }
	nodeList.add(pargumentNode1);
        return nodeList;
    }



    ArrayList new10()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PAssignValue passignvalueNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        passignvalueNode1 = new AAssignValue(pvalueNode2);
        }
	nodeList.add(passignvalueNode1);
        return nodeList;
    }



    ArrayList new11()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreArgs pmoreargsNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        tidNode2 = (TId)nodeArrayList2.get(0);

        pmoreargsNode1 = new AMoreArgs(tidNode2, null);
        }
	nodeList.add(pmoreargsNode1);
        return nodeList;
    }



    ArrayList new12()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreArgs pmoreargsNode1;
        {
        TId tidNode2;
        PAssignValue passignvalueNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        passignvalueNode3 = (PAssignValue)nodeArrayList3.get(0);

        pmoreargsNode1 = new AMoreArgs(tidNode2, passignvalueNode3);
        }
	nodeList.add(pmoreargsNode1);
        return nodeList;
    }



    ArrayList new13()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new14()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new15()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList2.get(0);
        pstatementNode3 = (PStatement)nodeArrayList4.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new16()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PComparison pcomparisonNode2;
        PStatement pstatementNode3;
        pcomparisonNode2 = (PComparison)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pcomparisonNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new17()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        pstatementNode4 = (PStatement)nodeArrayList6.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new18()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList3.get(0);
        tidNode3 = (TId)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AForStatement(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new19()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new20()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AReturnStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new21()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new22()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new23()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new24()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new APrintStatement(pexpressionNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new25()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AOpStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new26()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);

        pstatementNode1 = new AOpStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new27()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AListStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new28()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList7 = (ArrayList) pop();
        ArrayList nodeArrayList6 = (ArrayList) pop();
        ArrayList nodeArrayList5 = (ArrayList) pop();
        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList4.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList7.get(0);

        pstatementNode1 = new AListStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new29()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pstatementNode1 = new ACallStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new30()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PStatement pstatementNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList2.get(0);

        pstatementNode1 = new ACallStatement(pfunctioncallNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    ArrayList new31()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new32()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new33()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new34()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AListExpression(tidNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new35()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        }

        pexpressionNode1 = new AMorevaluesExpression(pvalueNode2, listNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new36()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pvalueNode2 = (PValue)nodeArrayList2.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList3.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new AMorevaluesExpression(pvalueNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new37()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PPrePostElements pprepostelementsNode2;
        pprepostelementsNode2 = (PPrePostElements)nodeArrayList2.get(0);

        pexpressionNode1 = new APrePlusPlusExpression(pprepostelementsNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new38()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PPrePostElements pprepostelementsNode2;
        pprepostelementsNode2 = (PPrePostElements)nodeArrayList2.get(0);

        pexpressionNode1 = new APreMinusMinusExpression(pprepostelementsNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new39()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PPrePostElements pprepostelementsNode2;
        pprepostelementsNode2 = (PPrePostElements)nodeArrayList1.get(0);

        pexpressionNode1 = new APostPlusPlusExpression(pprepostelementsNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new40()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PPrePostElements pprepostelementsNode2;
        pprepostelementsNode2 = (PPrePostElements)nodeArrayList1.get(0);

        pexpressionNode1 = new APostMinusMinusExpression(pprepostelementsNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new41()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPrePostElements pprepostelementsNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pprepostelementsNode1 = new AIdPrePostElements(tidNode2);
        }
	nodeList.add(pprepostelementsNode1);
        return nodeList;
    }



    ArrayList new42()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PPrePostElements pprepostelementsNode1;
        {
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pprepostelementsNode1 = new AListPrePostElements(tidNode2, pexpressionNode3);
        }
	nodeList.add(pprepostelementsNode1);
        return nodeList;
    }



    ArrayList new43()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreValues pmorevaluesNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList2.get(0);

        pmorevaluesNode1 = new AMoreValues(pvalueNode2);
        }
	nodeList.add(pmorevaluesNode1);
        return nodeList;
    }



    ArrayList new44()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new45()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAddExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new46()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ASubExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new47()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new48()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultiplicationExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new49()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ADivisionExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new50()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PValue pvalueNode2;
        pvalueNode2 = (PValue)nodeArrayList1.get(0);

        pexpressionNode1 = new AValueExpression(pvalueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new51()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpressionNode1 = new AIdExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new52()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PFunctionCall pfunctioncallNode2;
        pfunctioncallNode2 = (PFunctionCall)nodeArrayList1.get(0);

        pexpressionNode1 = new AFuncExpression(pfunctioncallNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new53()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PExpression pexpressionNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new AParenthesisExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    ArrayList new54()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {

        pcomparisonNode1 = new ATrueComparison();
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new55()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {

        pcomparisonNode1 = new AFalseComparison();
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new56()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AGreatComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new57()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ALessComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new58()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new AEqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new59()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PComparison pcomparisonNode1;
        {
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pcomparisonNode1 = new ANoteqComparison(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pcomparisonNode1);
        return nodeList;
    }



    ArrayList new60()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        Object nullNode3 = null;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pfunctioncallNode1 = new AFunctionCall(tidNode2, null);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new61()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList4 = (ArrayList) pop();
        ArrayList nodeArrayList3 = (ArrayList) pop();
        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PFunctionCall pfunctioncallNode1;
        {
        TId tidNode2;
        PArgList parglistNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        parglistNode3 = (PArgList)nodeArrayList3.get(0);

        pfunctioncallNode1 = new AFunctionCall(tidNode2, parglistNode3);
        }
	nodeList.add(pfunctioncallNode1);
        return nodeList;
    }



    ArrayList new62()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgList parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode3 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        }

        parglistNode1 = new AArgList(pexpressionNode2, listNode3);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new63()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PArgList parglistNode1;
        {
        PExpression pexpressionNode2;
        TypedLinkedList listNode4 = new TypedLinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        {
        TypedLinkedList listNode3 = new TypedLinkedList();
        listNode3 = (TypedLinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        parglistNode1 = new AArgList(pexpressionNode2, listNode4);
        }
	nodeList.add(parglistNode1);
        return nodeList;
    }



    ArrayList new64()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        PMoreExp pmoreexpNode1;
        {
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pmoreexpNode1 = new AMoreExp(pexpressionNode2);
        }
	nodeList.add(pmoreexpNode1);
        return nodeList;
    }



    ArrayList new65()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        PNumber pnumberNode2;
        pnumberNode2 = (PNumber)nodeArrayList1.get(0);

        pvalueNode1 = new ANumberValue(pnumberNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new66()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PValue pvalueNode1;
        {
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    ArrayList new67()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        PNumber pnumberNode1;
        {
        TInteger tintegerNode2;
        tintegerNode2 = (TInteger)nodeArrayList1.get(0);

        pnumberNode1 = new AIntNumber(tintegerNode2);
        }
	nodeList.add(pnumberNode1);
        return nodeList;
    }



    ArrayList new68()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PCommands pcommandsNode1;
        pcommandsNode1 = (PCommands)nodeArrayList1.get(0);
	if(pcommandsNode1 != null)
	{
	  listNode2.add(pcommandsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new69()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PCommands pcommandsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pcommandsNode2 = (PCommands)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcommandsNode2 != null)
	{
	  listNode3.add(pcommandsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new70()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMoreArgs pmoreargsNode1;
        pmoreargsNode1 = (PMoreArgs)nodeArrayList1.get(0);
	if(pmoreargsNode1 != null)
	{
	  listNode2.add(pmoreargsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new71()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMoreArgs pmoreargsNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmoreargsNode2 = (PMoreArgs)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmoreargsNode2 != null)
	{
	  listNode3.add(pmoreargsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new72()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        TTab ttabNode1;
        ttabNode1 = (TTab)nodeArrayList1.get(0);
	if(ttabNode1 != null)
	{
	  listNode2.add(ttabNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new73()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        TTab ttabNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        ttabNode2 = (TTab)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ttabNode2 != null)
	{
	  listNode3.add(ttabNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new74()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMoreExp pmoreexpNode1;
        pmoreexpNode1 = (PMoreExp)nodeArrayList1.get(0);
	if(pmoreexpNode1 != null)
	{
	  listNode2.add(pmoreexpNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new75()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMoreExp pmoreexpNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmoreexpNode2 = (PMoreExp)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmoreexpNode2 != null)
	{
	  listNode3.add(pmoreexpNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    ArrayList new76()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode2 = new TypedLinkedList();
        {
        PMoreValues pmorevaluesNode1;
        pmorevaluesNode1 = (PMoreValues)nodeArrayList1.get(0);
	if(pmorevaluesNode1 != null)
	{
	  listNode2.add(pmorevaluesNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    ArrayList new77()
    {
        ArrayList nodeList = new ArrayList();

        ArrayList nodeArrayList2 = (ArrayList) pop();
        ArrayList nodeArrayList1 = (ArrayList) pop();
        TypedLinkedList listNode3 = new TypedLinkedList();
        {
        TypedLinkedList listNode1 = new TypedLinkedList();
        PMoreValues pmorevaluesNode2;
        listNode1 = (TypedLinkedList)nodeArrayList1.get(0);
        pmorevaluesNode2 = (PMoreValues)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmorevaluesNode2 != null)
	{
	  listNode3.add(pmorevaluesNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {0, SHIFT, 1}, {15, SHIFT, 2}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, REDUCE, 72}, },
			{{-1, ERROR, 2}, {30, SHIFT, 16}, },
			{{-1, ERROR, 3}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {27, SHIFT, 21}, {28, SHIFT, 22}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 4}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {27, SHIFT, 21}, {28, SHIFT, 22}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 5}, {30, SHIFT, 38}, },
			{{-1, ERROR, 6}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 7}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 8}, {12, SHIFT, 41}, {16, SHIFT, 42}, {18, SHIFT, 43}, },
			{{-1, ERROR, 9}, {32, ACCEPT, -1}, },
			{{-1, REDUCE, 68}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 1}, {0, SHIFT, 1}, {15, SHIFT, 2}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 15}, {0, SHIFT, 45}, {21, SHIFT, 46}, {22, SHIFT, 47}, {23, SHIFT, 48}, {25, SHIFT, 49}, {26, SHIFT, 50}, {30, SHIFT, 51}, },
			{{-1, ERROR, 16}, {16, SHIFT, 53}, },
			{{-1, ERROR, 17}, {30, SHIFT, 54}, },
			{{-1, ERROR, 18}, {30, SHIFT, 54}, },
			{{-1, ERROR, 19}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 20}, {29, SHIFT, 23}, {31, SHIFT, 25}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 67}, },
			{{-1, REDUCE, 51}, {1, REDUCE, 41}, {2, REDUCE, 41}, {16, SHIFT, 42}, {18, SHIFT, 59}, },
			{{-1, REDUCE, 66}, },
			{{-1, ERROR, 26}, {5, SHIFT, 60}, {6, SHIFT, 61}, {13, SHIFT, 62}, {14, SHIFT, 63}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 33}, },
			{{-1, ERROR, 29}, {1, SHIFT, 64}, {2, SHIFT, 65}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 44}, {8, SHIFT, 66}, {9, SHIFT, 67}, {10, SHIFT, 68}, {11, SHIFT, 69}, },
			{{-1, REDUCE, 47}, },
			{{-1, ERROR, 33}, {7, SHIFT, 70}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 50}, },
			{{-1, REDUCE, 65}, },
			{{-1, ERROR, 37}, {7, SHIFT, 71}, },
			{{-1, ERROR, 38}, {24, SHIFT, 72}, },
			{{-1, REDUCE, 21}, {20, SHIFT, 73}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 41}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 42}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {17, SHIFT, 77}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 43}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, REDUCE, 69}, },
			{{-1, REDUCE, 73}, },
			{{-1, ERROR, 46}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {27, SHIFT, 21}, {28, SHIFT, 22}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 47}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {27, SHIFT, 21}, {28, SHIFT, 22}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 48}, {30, SHIFT, 83}, },
			{{-1, ERROR, 49}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 50}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 51}, {12, SHIFT, 86}, {16, SHIFT, 42}, {18, SHIFT, 87}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 53}, {17, SHIFT, 88}, {30, SHIFT, 89}, },
			{{-1, REDUCE, 41}, {18, SHIFT, 91}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 57}, {17, SHIFT, 92}, },
			{{-1, ERROR, 58}, {19, SHIFT, 93}, {20, SHIFT, 94}, },
			{{-1, ERROR, 59}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 60}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 61}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 62}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 63}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 66}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 67}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 68}, {16, SHIFT, 19}, {29, SHIFT, 23}, {30, SHIFT, 104}, {31, SHIFT, 25}, },
			{{-1, ERROR, 69}, {16, SHIFT, 19}, {29, SHIFT, 23}, {30, SHIFT, 104}, {31, SHIFT, 25}, },
			{{-1, ERROR, 70}, {0, SHIFT, 1}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 71}, {0, SHIFT, 1}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 72}, {30, SHIFT, 109}, },
			{{-1, ERROR, 73}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, REDUCE, 74}, },
			{{-1, REDUCE, 23}, {20, SHIFT, 73}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 60}, },
			{{-1, REDUCE, 62}, {20, SHIFT, 73}, },
			{{-1, ERROR, 79}, {17, SHIFT, 113}, },
			{{-1, ERROR, 80}, {19, SHIFT, 114}, },
			{{-1, ERROR, 81}, {7, SHIFT, 115}, },
			{{-1, ERROR, 82}, {7, SHIFT, 116}, },
			{{-1, ERROR, 83}, {24, SHIFT, 117}, },
			{{-1, REDUCE, 22}, {20, SHIFT, 73}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 86}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 87}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, ERROR, 88}, {7, SHIFT, 121}, },
			{{-1, REDUCE, 6}, {12, SHIFT, 122}, {20, SHIFT, 123}, },
			{{-1, ERROR, 90}, {17, SHIFT, 127}, },
			{{-1, ERROR, 91}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 94}, {29, SHIFT, 23}, {31, SHIFT, 25}, },
			{{-1, REDUCE, 76}, },
			{{-1, ERROR, 96}, {19, SHIFT, 130}, {20, SHIFT, 94}, },
			{{-1, ERROR, 97}, {19, SHIFT, 132}, },
			{{-1, REDUCE, 58}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 57}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 51}, {16, SHIFT, 42}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 109}, {7, SHIFT, 133}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 75}, },
			{{-1, REDUCE, 63}, {20, SHIFT, 73}, },
			{{-1, REDUCE, 61}, },
			{{-1, ERROR, 114}, {12, SHIFT, 134}, },
			{{-1, ERROR, 115}, {0, SHIFT, 1}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 116}, {0, SHIFT, 1}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 117}, {30, SHIFT, 137}, },
			{{-1, REDUCE, 24}, {20, SHIFT, 73}, },
			{{-1, REDUCE, 26}, },
			{{-1, ERROR, 120}, {19, SHIFT, 138}, },
			{{-1, ERROR, 121}, {0, SHIFT, 1}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 122}, {29, SHIFT, 23}, {31, SHIFT, 25}, },
			{{-1, ERROR, 123}, {30, SHIFT, 141}, },
			{{-1, REDUCE, 7}, {20, SHIFT, 123}, },
			{{-1, REDUCE, 70}, },
			{{-1, REDUCE, 8}, {20, SHIFT, 123}, },
			{{-1, ERROR, 127}, {7, SHIFT, 144}, },
			{{-1, ERROR, 128}, {19, SHIFT, 145}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 77}, },
			{{-1, REDUCE, 34}, {1, REDUCE, 42}, {2, REDUCE, 42}, },
			{{-1, ERROR, 133}, {0, SHIFT, 1}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 134}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 137}, {7, SHIFT, 148}, },
			{{-1, ERROR, 138}, {12, SHIFT, 149}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 11}, {12, SHIFT, 122}, },
			{{-1, REDUCE, 9}, {20, SHIFT, 123}, },
			{{-1, REDUCE, 71}, },
			{{-1, ERROR, 144}, {0, SHIFT, 1}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 148}, {0, SHIFT, 1}, {21, SHIFT, 3}, {22, SHIFT, 4}, {23, SHIFT, 5}, {25, SHIFT, 6}, {26, SHIFT, 7}, {30, SHIFT, 8}, },
			{{-1, ERROR, 149}, {1, SHIFT, 17}, {2, SHIFT, 18}, {16, SHIFT, 19}, {18, SHIFT, 20}, {29, SHIFT, 23}, {30, SHIFT, 24}, {31, SHIFT, 25}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 28}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 9}, },
			{{-1, 10}, {14, 44}, },
			{{-1, 11}, },
			{{-1, 90}, },
			{{-1, 124}, {141, 150}, },
			{{-1, 125}, {126, 143}, {142, 143}, },
			{{-1, 12}, {70, 107}, {71, 108}, {115, 135}, {116, 136}, {121, 139}, {133, 146}, {144, 151}, {148, 152}, },
			{{-1, 26}, {6, 39}, {7, 40}, {19, 57}, {41, 76}, {42, 78}, {43, 80}, {49, 84}, {50, 85}, {59, 97}, {60, 98}, {61, 99}, {62, 100}, {63, 101}, {66, 102}, {67, 103}, {73, 110}, {86, 119}, {87, 120}, {91, 128}, {134, 147}, {149, 153}, },
			{{-1, 27}, },
			{{-1, 28}, },
			{{-1, 29}, {17, 55}, {18, 56}, },
			{{-1, 95}, {96, 131}, },
			{{-1, 30}, },
			{{-1, 31}, },
			{{-1, 32}, {68, 105}, {69, 106}, },
			{{-1, 33}, {4, 37}, {46, 81}, {47, 82}, },
			{{-1, 34}, {0, 13}, {14, 13}, {15, 52}, {70, 13}, {71, 13}, {115, 13}, {116, 13}, {121, 13}, {133, 13}, {144, 13}, {148, 13}, },
			{{-1, 79}, },
			{{-1, 74}, {75, 111}, {112, 111}, {118, 111}, },
			{{-1, 35}, {20, 58}, {94, 129}, {122, 140}, },
			{{-1, 36}, },
			{{-1, 14}, },
			{{-1, 126}, {124, 142}, },
			{{-1, 15}, },
			{{-1, 75}, {78, 112}, {84, 118}, },
			{{-1, 96}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: tab, 'def', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: tab, 'if', 'while', 'for', 'print', 'return', id",
			"expecting: id",
			"expecting: '++', '--', '(', '[', 'true', 'false', integer, id, string",
			"expecting: '++', '--', '(', '[', integer, id, string",
			"expecting: '=', '(', '['",
			"expecting: EOF",
			"expecting: '('",
			"expecting: integer, string",
			"expecting: ':'",
			"expecting: tab, '==', '!=', ':', '+', '-', '*', '/', '<', '>', 'def', ')', ']', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: tab, '++', '--', '==', '!=', ':', '+', '-', '*', '/', '<', '>', 'def', '(', ')', '[', ']', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: '==', '!=', '<', '>'",
			"expecting: tab, '==', '!=', ':', '<', '>', 'def', ')', ']', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: '++', '--'",
			"expecting: 'in'",
			"expecting: tab, 'def', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: '++', '--', '(', ')', '[', integer, id, string",
			"expecting: ')', id",
			"expecting: tab, '==', '!=', ':', '<', '>', 'def', ')', '[', ']', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: ')'",
			"expecting: ']', ','",
			"expecting: '(', integer, id, string",
			"expecting: tab, 'def', ')', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: ')', ','",
			"expecting: ']'",
			"expecting: '=', ')', ','",
			"expecting: tab, '==', '!=', ':', '+', '-', '*', '/', '<', '>', 'def', '(', ')', ']', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
			"expecting: '='",
			"expecting: tab, '++', '--', '==', '!=', ':', '<', '>', 'def', ')', ']', ',', 'if', 'while', 'for', 'print', 'return', id, EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 2, 4, 4, 5, 6, 0, 0, 0, 0, 0, 1, 7, 2, 2, 4, 8, 9, 9, 10, 11, 10, 12, 13, 13, 14, 13, 10, 10, 9, 10, 10, 10, 9, 15, 16, 0, 4, 17, 4, 0, 1, 3, 3, 2, 4, 4, 5, 0, 18, 19, 13, 13, 20, 21, 4, 4, 4, 4, 4, 13, 13, 4, 4, 22, 22, 1, 1, 2, 4, 23, 16, 0, 10, 24, 20, 25, 9, 9, 15, 16, 0, 4, 4, 9, 26, 20, 4, 10, 13, 8, 21, 21, 25, 9, 9, 9, 9, 13, 13, 27, 10, 10, 0, 0, 9, 23, 23, 24, 10, 28, 1, 1, 2, 16, 0, 25, 1, 8, 2, 24, 24, 24, 9, 25, 21, 13, 21, 29, 1, 4, 0, 0, 9, 28, 0, 24, 26, 24, 24, 1, 13, 0, 0, 1, 4, 24, 0, 0, 0, 
        };*/
}
