/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AArgArgument extends PArgument
{
    private TId _id_;
    private PAssignValue _assignValue_;
    private final LinkedList _moreArgs_ = new TypedLinkedList(new MoreArgs_Cast());

    public AArgArgument()
    {
    }

    public AArgArgument(
        TId _id_,
        PAssignValue _assignValue_,
        List _moreArgs_)
    {
        setId(_id_);

        setAssignValue(_assignValue_);

        {
            this._moreArgs_.clear();
            this._moreArgs_.addAll(_moreArgs_);
        }

    }
    public Object clone()
    {
        return new AArgArgument(
            (TId) cloneNode(_id_),
            (PAssignValue) cloneNode(_assignValue_),
            cloneList(_moreArgs_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgArgument(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public PAssignValue getAssignValue()
    {
        return _assignValue_;
    }

    public void setAssignValue(PAssignValue node)
    {
        if(_assignValue_ != null)
        {
            _assignValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _assignValue_ = node;
    }

    public LinkedList getMoreArgs()
    {
        return _moreArgs_;
    }

    public void setMoreArgs(List list)
    {
        _moreArgs_.clear();
        _moreArgs_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_assignValue_)
            + toString(_moreArgs_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_assignValue_ == child)
        {
            _assignValue_ = null;
            return;
        }

        if(_moreArgs_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(_assignValue_ == oldChild)
        {
            setAssignValue((PAssignValue) newChild);
            return;
        }

        for(ListIterator i = _moreArgs_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class MoreArgs_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMoreArgs node = (PMoreArgs) o;

            if((node.parent() != null) &&
                (node.parent() != AArgArgument.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AArgArgument.this))
            {
                node.parent(AArgArgument.this);
            }

            return node;
        }
    }
}
