/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class APrePlusPlusExpression extends PExpression
{
    private PPrePostElements _prePostElements_;

    public APrePlusPlusExpression()
    {
    }

    public APrePlusPlusExpression(
        PPrePostElements _prePostElements_)
    {
        setPrePostElements(_prePostElements_);

    }
    public Object clone()
    {
        return new APrePlusPlusExpression(
            (PPrePostElements) cloneNode(_prePostElements_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrePlusPlusExpression(this);
    }

    public PPrePostElements getPrePostElements()
    {
        return _prePostElements_;
    }

    public void setPrePostElements(PPrePostElements node)
    {
        if(_prePostElements_ != null)
        {
            _prePostElements_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _prePostElements_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_prePostElements_);
    }

    void removeChild(Node child)
    {
        if(_prePostElements_ == child)
        {
            _prePostElements_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_prePostElements_ == oldChild)
        {
            setPrePostElements((PPrePostElements) newChild);
            return;
        }

    }
}
