/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TMinusMinus extends Token
{
    public TMinusMinus()
    {
        super.setText("--");
    }

    public TMinusMinus(int line, int pos)
    {
        super.setText("--");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMinusMinus(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMinusMinus(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMinusMinus text.");
    }
}
